"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const random_1 = require("./src/random");
const pointselector_1 = require("./src/voronoi/pointselector");
const voronoimapfilter_1 = require("./src/filters/voronoimapfilter");
const browser_1 = require("./browser");
let r = new random_1.Random(123);
let mapw = 1900;
let maph = 944;
let points = pointselector_1.PointSelector.GeneratePointsJittered(1000, mapw, maph, r);
let filter = new voronoimapfilter_1.VoronoiMapFilter(mapw, maph);
filter.CreateGraph(points, pointselector_1.PointSelector.NUM_LLOYD_RELAXATIONS);
console.log(filter.graph.sites.Count);
console.log(filter.cells.length);
var browser = new browser_1.Browser();
browser.Draw(filter.cellsByID[547]);
